apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka
  labels:
    app: kafka-app
spec:
  selector:
    app: kafka-app
  type: ClusterIP
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      initContainers:
      - name: format-kafka
        image: doughgle/kafka-kraft
        command: ["/opt/kafka/bin/kafka-storage.sh", "format", "-t", "xtzWWN4bTjitpL3kfd9s5g", "--config", "/opt/kafka/config/kraft/server.properties"]
        volumeMounts:
        - name: data
          mountPath: /mnt/kafka
      containers:
      - name: kafka-container
        image: doughgle/kafka-kraft
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: REPLICAS
          value: "3"
        - name: SERVICE
          value: kafka-svc
        - name: NAMESPACE
          value: kafka
        - name: SHARE_DIR
          value: /mnt/kafka
        - name: CLUSTER_ID
          value: xtzWWN4bTjitpL3kfd9s5g
        - name: DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: DEFAULT_MIN_INSYNC_REPLICAS
          value: "2"
        volumeMounts:
        - name: data
          mountPath: /mnt/kafka
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 64Mi
